# -*- coding: utf-8 -*-
"""DS_D5_Support_Vector_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VoGySO-ghvDk1Vu1V5IJr-ANrOo_lYG_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVR

df=pd.read_csv("Downloads/heart.csv")

df.head()

x = pd.DataFrame(df.iloc[:,0])
y = pd.DataFrame(df.iloc[:,7])

from sklearn.model_selection import train_test_split
xtr,xte,ytr,yte=train_test_split(x,y)
reg = SVR(kernel="rbf")
reg.fit(xtr,ytr)

plt.scatter(x,y)
plt.plot(xte,reg.predict(xte),color="r")

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x=sc.fit_transform(x)
y=sc.fit_transform(y)
xtr,xte,ytr,yte=train_test_split(x,y)
reg = SVR(kernel="rbf")
reg.fit(xtr,ytr)

plt.scatter(x,y)
plt.plot(xte,reg.predict(xte),color="r")

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

ypred=reg.predict(xte)
print(mean_absolute_error(yte,ypred))
print(mean_squared_error(yte,ypred))
print(r2_score(yte,ypred))

