# -*- coding: utf-8 -*-
"""DS_D3_Multiple_Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X7UC4BrZTCpMrFVMWJ6yYnm_jTVzevyo

# Multiple Linear Regression
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df= pd.read_csv("heart.csv")

df.head()

x= df.iloc[:,[0,3,4]]
y= pd.DataFrame(df.iloc[:,7])

reg = LinearRegression()

xtr,xte,ytr,yte=train_test_split(x,y,test_size=0.25)

reg.fit(xtr,ytr)

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

print(mean_absolute_error(yte,reg.predict(xte)))
print(mean_squared_error(yte,reg.predict(xte)))
print(r2_score(yte,reg.predict(xte)))

